digraph G {
n1[label="<ROOT>", color="green"];
n2[label="Makefile", color="green"];
n3[label="all", color="red"];
n4[label="article.Rmd", color="green"];
n6[label="article.html", color="red"];
n7[label="article.md", color="red"];
n5[label="figure.gv", color="green"];
n8[label="figure.png", color="red"];
n2 -> n1 ; 
n3 -> n1 ; 
n4 -> n3 ; 
n6 -> n3 ; 
n5 -> n3 ; 
n4 -> n6 ; 
n7 -> n6 ; 
n5 -> n6 ; 
n8 -> n6 ; 
n4 -> n7 ; 
n5 -> n8 ; 
}
