---
output:
  html_document:
    toc: true
    toc_depth: 4
---

### cm003 2015-09-13 Tuesday overview

  * Please take this survey (yes of course it's a Shiny app!):
    - <http://shiny.stat.ubc.ca/STAT545/stat545-basic-info/>
    - this is how we get your GitHub username, match you against the course list, and give you a private course repository within the [STAT 545 Organization](https://github.com/STAT545-UBC)
    - username and password for survey given in class
  * Quick live look at "who's in here?" (see below)
  * Revisit toy line script from last class, which covered:
    - [R basics, workspace and working directory, RStudio projects](block002_hello-r-workspace-wd-project.html)
    - Do "Compile Notebook" on it!
  * Work on "Connect Git, GitHub, RStudio" and "Early GitHub Usage" from  <http://happygitwithr.com>
    - If you see slides, they'll be something like these:  <https://speakerdeck.com/jennybc/happy-git-and-github-for-the-user>
    - Goal: [New project, GitHub first](http://happygitwithr.com/new-github-first.html)
  * What's coming?
    - DATA!!
    - Exploring the Gapminder data
    - `data.frame`
    - `ggplot2`
  * First homework will be due midnight Tuesday September 20, but preferably before class. Go to office hours if struggling! See the [2015 version here](hw01_edit-README.html) (some changes still coming).

### Good question: who's in this class?

I did some live analysis of the course list. Here's one cross-tabulation.

```{r echo = FALSE, results = 'asis'}
whos_in_here <- 'spec1_subject,BSC,Msthg,PHD,UNCL,total
Psychology,0.0,2.0,6.0,0.0,8.0
Statistics,0.0,7.0,0.0,0.0,7.0
Bioinformatics,0.0,5.0,0.0,0.0,5.0
Forestry,0.0,4.0,1.0,0.0,5.0
NA,0.0,2.0,0.0,3.0,5.0
Computer Science,0.0,4.0,0.0,0.0,4.0
Electrical & Computer Eng,0.0,4.0,0.0,0.0,4.0
"Resources,Enviro & Sustain",0.0,4.0,0.0,0.0,4.0
Zoology,0.0,3.0,1.0,0.0,4.0
Geography,0.0,2.0,1.0,0.0,3.0
Kinesiology,0.0,2.0,1.0,0.0,3.0
Population and Public Health,0.0,2.0,1.0,0.0,3.0
Experimental Medicine,0.0,1.0,1.0,0.0,2.0
Genome Science & Technology,0.0,2.0,0.0,0.0,2.0
Microbiology and Immunology,2.0,0.0,0.0,0.0,2.0
Neuroscience,0.0,1.0,1.0,0.0,2.0
Civil Engineering,0.0,1.0,0.0,0.0,1.0
"Human Devl,Learning & Culture",0.0,1.0,0.0,0.0,1.0
Human Kinetics,0.0,0.0,1.0,0.0,1.0
Linguistics,0.0,0.0,1.0,0.0,1.0
Mathematics,0.0,0.0,1.0,0.0,1.0
Mechanical Engineering,0.0,1.0,0.0,0.0,1.0
Medical Genetics,0.0,1.0,0.0,0.0,1.0
Microbiology & Immunology,0.0,0.0,1.0,0.0,1.0
Oceanography,0.0,0.0,1.0,0.0,1.0
Pharmacology,0.0,1.0,0.0,0.0,1.0
Physics,0.0,0.0,1.0,0.0,1.0
Plant Science,0.0,1.0,0.0,0.0,1.0
Resource Mgmt/Envirn Stud,0.0,1.0,0.0,0.0,1.0
'
wih <- readr::read_csv(whos_in_here)
knitr::kable(wih)
```

