---
title: "FAQ"
output:
  html_document:
    toc: true
    toc_depth: 3
    includes:
      after_body: include/nothing.html
---

### Course facts

|          | STAT 545A                       | STAT547M                        |
|----------|---------------------------------|---------------------------------|
| title    | Exploratory Data Analysis       | Basic Training for Data Science |
| SSC link | [STAT 545A][SSC 545A]           | [STAT 547M][SSC 547M]           |
| credits  | 1.5                             | 1.5                             |
| dates    | Sep 02, 2014 to Oct 19, 2014    | Oct 20, 2014 to Nov 28, 2014    |
| meets    | Mon Wed 9:30 - 11am             | Mon Wed 9:30 - 11am             |
| where    | [GEOG 200][geog200] (new!)      | [GEOG 200][geog200] (new!)      |
| pre-req  | none (but see below)            | STAT 545A                       |

[esb1042]: http://www.maps.ubc.ca/?225
[geog200]: http://www.students.ubc.ca/classroomservices/buildings-and-classrooms/?code=GEOG&room=200
[SSC 545A]: https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=STAT&course=545A&section=101
[SSC 547M]: https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=STAT&course=547M&section=101

### What's up with the two half courses?

For several years, I have taught STAT 545A as a 1.5 credit course. I -- and many students -- have felt there was alot of great, relevant content that could go into an additional 1.5 credits.

Therefore, in 2014/2015, we will pilot a full semester on data exploration, visualization, and all-around data wrangling. It is structured as two half courses for various reasons, such as allowing STAT 545A alums to register for STAT 547M and get the "missing half" of the course!

### Am I allowed to register in ...?

  * I have taken STAT 545A for 1.5 credits in the past. Can I take STAT 547M?
    - YES. But you will want to follow along during STAT 545A (at least online), so you get some new content. Examples: the use of Git for version control, GitHub for collaboration, `knitr` and R Markdown for dynamic documents, `ggplot2` for graphics, `plyr` and `dplyr` for data aggregation.
  * Can I just take the second half, i.e. STAT 547M?
    - NO, not unless you have taken STAT 545A previously.
  * Can I take just the first half, i.e. STAT 545A?
    - YES. But development is proceeding with the ultimate goal of creating a full 3 credit course. I will try to make each half stand alone reasonably well, but that is not my top priority.
  * What do you advise I do?
    - Take STAT 545A and STAT 547M!
  * Can I audit?
    - PROBABLY. Come talk to me.
    - Official auditing instructions for UBC [undergrads](http://students.ubc.ca/enrolment/courses/academic-planning/audit) and [graduate students](http://www.grad.ubc.ca/current-students/managing-your-program/audit)
  * I am an unclassified student, SFU student, UBC undergradate, etc. Can I take the course?
    - PROBABLY. Come talk to me.
  * What if I've never had a stats class?
    - There are no official pre-requisites for STAT 545A but most students will have had at least one prior statistics course.

### Should I register in ...?

This course is open to any graduate student at UBC. Students from other departments generally outnumber those from Statistics. In fact, the most successful students are often grad students from other fields who need to analyze and visualize data for a thesis. They are highly motivated and excel.

However, __if you have never programmed or worked at the command line before, prepare for a shock.__ This will be a powerful, positive experience, but it's a big adjustment. Come suffer through the worst part of the learning curve in good company!

### Do I need a computer?

YES. You absolutely must have access to a computer on which you can install software, download data, etc. In fact, *class meetings* will be a mix of lecture, discussion, and live coding. Students will get the most out of this if they can bring their own laptop to class every day. If this is not possible, we will try to help you work something out.
