---
title: "Data from the Web - Homework"
author: "Andrew MacDonald and Jenny Bryan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 4
---

## Big picture

We learned three ways of collecting data from the internet:

  * Accessing data using ROpenSci packages that wrap APIs
  * Running (basic) API queries "by hand"
  * Web scraping

For the homework, we want you to either

  * combine two existing datasets in a novel (and reproducible!) way; at least one must come from the web
  * create a new dataset by web scraping

## Please just tell me what to do! 

### Combine `gapminder` and data from `geonames`

Use data from both to investigate either of these questions:

  * What is the relationship between per-capita GDP and the proportion of the population which lives in urban centers?
  * Consider the following graph of population against time (a modification of Jenny's [gapminder demo](https://github.com/jennybc/gapminder)):
    
```{r spaghetti-plot-pop-vs-year, message = FALSE}
library("ggplot2")
library("gapminder")

ggplot(subset(gapminder, continent != "Oceania"),
       aes(x = year, y = pop, group = country, color = country)) +
  geom_line(lwd = 1, show_guide = FALSE) + facet_wrap(~ continent) +
  scale_color_manual(values = country_colors) +
  theme_bw() + theme(strip.text = element_text(size = rel(1.1))) + scale_y_log10()
```

Replace population with *density*. To do this, look up the country codes in `geonames()`, obtain the area of each country and compute density as population divided by area.

Write and render an RMarkdown document with a narrative of what you've done and why and the code that does it. What was most difficult? What are you most excited about re: your future in getting data from the web?

Your procedure for obtaining and remixing data should be reproducible and, ideally, portable to your peer's system (no more `setwd()`!).

## Combine two datasets

  * `rplos` and `rebird` -- how many articles are published on a bird species? 
  * `rplos` and `geonames` -- Choose a random set of countries. How many papers have been published by people from that country? In that country? how does that relate to GDP (will require expert-level regex skills)
  * `rebird` and `geonames` -- Do countries with more bird species also have more languages?

## I want to aim higher!

* Go look through the RopenSci [packages list](http://ropensci.org/packages/) and/or the Ropensci [Web Services in R](https://github.com/ropensci/webservices), find some existing resources, and remix those instead.

## even HIGHER

* Consult [programmable web](), discover an API which is NOT wrapped by Ropensci (yet!) and write a function to query that.

## I am a leaf on the wind. See how I SOAR

  * Find an interesting website which is a) __not__ on Ropensci __nor__ b) has a published API. Scrape it into a lovely dataset for us, and publish this as a data package a la Gapminder .

### Due date

Your homework is due Friday 05 December 2014.

## Rubric

Ideally you will actually *run* your peer's code and get the same results! Again, you're welcome to abandon the effort after 30 mins and provide feedback.

Recall the [general homework rubric](http://stat545-ubc.github.io/peer-review01_marking-rubric.html).

